config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'user#my_done_days'
   get '/login' => 'user#login_home', :as => :login

   post '/save_details' => 'user#save_details', :as => :save_user
   get '/users/', :to => 'user#update_details', :as => :user
   patch '/save_details', :to => 'user#save_details'
   get '/days/', :to => 'user#my_done_days', :as => :my_done_days
   get '/calender/', :to => 'user#calender'
   get '/submit/:date', :to => 'user#submit_run'

   get '/super_submit/:id/:date', :to => 'user#submit_super_run'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :runs
  has_many :users, :through => :runs

  def start_time
      self.day
  end
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :day
  belongs_to :user

  def start_time
      self.day.day
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :runs
  has_many :days, :through => :runs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:strava]


         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.reporting_email = auth.info.email
             user.password = Devise.friendly_token[0,20]
             user.firstname = auth.info.first_name
             user.lastname = auth.info.last_name
             user.access_token = auth.credentials.token
             user.profile = auth.extra.raw_info.profile
             #user.image = auth.info.image # assuming the user model has an image
             # If you are using confirmable and the provider(s) you use validate emails,
             # uncomment the line below to skip the confirmation emails.
             # user.skip_confirmation!
           end

           user = where(provider: auth.provider, uid: auth.uid).first
           #logger.debug "access_token check  #{!(user.access_token.eql? auth.credentials.token)} auth #{auth.credentials.token} our token #{user.access_token}"
           if !(user.access_token.eql? auth.credentials.token)
             user.update(access_token: auth.credentials.token)
           end
           return user
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def strava
    # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Strava") if is_navigational_format?
      redirect_to user_path
    else
      session["devise.strava_data"] = request.env["omniauth.auth"]
      redirect_to user_path
    end
  end

  def failure
    redirect_to login_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :require_login, except: [:login_home]

  def login_home
    #if user_signed_in?
    #  redirect_to current_user
    #end
    @affix_value = 100
  end

  def update_details
    @user = current_user
  end

  def save_details
    user = current_user
    user.update!(user_params)
    PostWorker.perform_async(current_user.id, DateTime.now.strftime("%Y-%m-%d"))
    redirect_to root_path
  end

  def my_done_days
      PostWorker.perform_async(current_user.id, DateTime.now.strftime("%Y-%m-%d"))
      @runs = current_user.runs.order(day_id: :asc)
      @missing_days = Day.where.not(:id => @runs.map(&:day_id)).where("day >= ?", 1.week.ago).where("day <= ?", Time.now )
  end

  def calender
      PostWorker.perform_async(current_user.id, DateTime.now.strftime("%Y-%m-%d"))
      @runs = current_user.runs.order(day_id: :asc)
      @missing_days = Day.where.not(:id => @runs.map(&:day_id)).where("day >= ?", 1.week.ago).where("day <= ?", Time.now )
  end

  def submit_run
    PostWorker.perform_async(current_user.id, params['date'])
    redirect_to my_done_days_path
  end

  def submit_super_run
    PostWorker.perform_async(params['id'], params['date'])
    redirect_to my_done_days_path
  end

  private

  def user_params
        params.require(:user).permit(:dob, :reporting_email)
  end

  def submit_params
    params.permit(:date, :user_id)
  end

  def require_login
  unless current_user
    redirect_to login_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Hundreddaysrunning - Strava Sync </title>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<meta property="og:url"                content="http://hundreddaysrunning.pnplab.in/" />
<meta property="og:type"               content="website" />
<meta property="og:title"              content="Sync strava data to 100daysofrunning challange" />
<meta property="og:description"        content="Effortlessly sync your runs in strava with 100days running challenge" />
<meta property="og:image"              content=<%=image_url('breaker-bg.jpg')%> />

<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" integrity="sha384-0s5Pv64cNZJieYFkXYOTId2HMA2Lfb6q2nAcx2n0RTLUnCAoTTsS0nKEO27XyKcY" crossorigin="anonymous"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" integrity="sha384-ZoaMbDF+4LeFxg6WdScQ9nnR1QC2MIRxA1O9KWEXQwns1G8UNyIEZIQidzb0T1fo" crossorigin="anonymous"></script>
<![endif]-->
<!-- Plugin JavaScript -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" integrity="sha384-mE6eXfrb8jxl0rzJDBRanYqgBxtJ6Unn4/1F7q4xRRyIw7Vdg9jP4ycT7x1iVsgb" crossorigin="anonymous"></script>

  <!-- Navigation -->
  <nav id="mainNav"  <% if @affix_value != nil && (@affix_value > 0) %>  data-spy="affix" data-offset-top=<%= @affix_value%>  <%end%>   class="navbar navbar-default navbar-custom navbar-fixed-top <% if @affix_value == nil ||  (@affix_value.eql? 0) %> affix <%end%>">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand page-scroll" href="/login/">Hundreddaysrunning - Strava Sync </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li class="hidden">
                      <a href="#page-top"></a>
                  </li>
                  <li>
                      <a class="page-scroll" href="/login#about">Configuration</a>
                  </li>
                  <li>
                      <a class="page-scroll" href="/login#services">Features</a>
                  </li>
                  <li>
                      <a class="page-scroll" href="/days/">Runs</a>
                  </li>
                  <li>
                      <a class="page-scroll" href="/users/">Details</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/calender.html.erb
<div class="nonheadimage">
<%= month_calendar events: @runs do |date, meetings| %>
  <%= date.day %>
  <% if meetings.first %>
  <div>
    Day #<%= meetings.first.day.id %> </br>
    Date: <%= meetings.first.day.day %> </br>
    Distance:  <%= meetings.first.distance %> </br>
    Time: <%= meetings.first.time %> </br>
    Run Link: <%= meetings.first.link %>
    <% if meetings.first.day.day >= 1.week.ago && meetings.first.day.day <= Time.now %>

     <a role="button" href="/submit/<%=meetings.first.day.day%>" class="btn btn-default">Resubmit Run</button>
      <% end %>

  </div>
  <%end%>

<% end %>

app/views/user/home.html.erb
<%= link_to "Sign in with Strava", user_strava_omniauth_authorize_path %>

app/views/user/login_home.html.erb
<!--<%= link_to "Sign in with Strava", user_strava_omniauth_authorize_path %>-->


<!-- Header -->
<header>
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Sync daily runs to 100 days challange. </div>
            <div class="intro-heading">Seamlessly</div>
            <a href=<%=user_strava_omniauth_authorize_path%> class="page-scroll btn btn-xl">Signup with strava</a>
        </div>
    </div>
</header>

<!-- Services Section -->
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Features</h2>
                <h3 class="section-subheading text-muted">Sync daily run from strava to 100 days running challenge.</h3>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Seamless</h4>
                <p class="text-muted">It automatically sync your runs from strava to 100 days running challange without doing anything.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Resubmit old runs</h4>
                <p class="text-muted"> Check the runs which are currently submitted and resubmit any run again upto last 7 days.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Notification</h4>
                <p class="text-muted">We are also working on notifing you if you haven't run today by 10PM IST to remind you to finish your todays run.</p>
            </div>
        </div>
    </div>
</section>



<!-- About Section -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">How it works</h2>
                <h3 class="section-subheading text-muted">Steps you need to follow to configure your run.</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <ul class="timeline">
                    <li>
                        <div class="timeline-image">
                          <h2>Step <br> 1 </h2>

                          <!--  <img class="img-circle img-responsive" src="img/about/1.jpg" alt="">-->
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 >Signup using Strava</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">Clikc on link above to sign up with Strava!</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                          <h2>Step <br> 2 </h2>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 > Update Date of birth</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">Update your date of birth in record section</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image">
                          <h2>Step <br> 3 </h2>

                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 >Update reporting_email </h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">Reporting email is defaulted to strava email, update the email id if your 100 days of running registered email is different from strava email.!</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                          <h2>Step <br> 4 </h2>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4> Check your runs</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted"> Go to run section and check if your runs are reported correctly and resubmit any old run you haven't submitted!</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <h4>Now you
                                <br>Should be
                                <br>Done!</h4>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

app/views/user/my_done_days.html.erb
<div class="nonheadimage">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Your Runs</div>
  <div class="panel-body">
    <p>
      Resubmit Run will try to post your data in background. Please don't resubmit again and again.
      Refresh this page after sometime to check updated runs after your recent request is processed.
    </p>
  </div>
  <!-- Table -->
  <table class="table table-condensed   center_div">

 <tr>
   <th>Date</th>
   <th>Distance</th>
   <th>Time</th>
   <th>Run link</th>
   <th>Resubmit Run</th>
 </tr>
 <%  @missing_days.each do |missing| %>


   <tr>
     <td>
       <%= missing.day        %>
     </td>
     <td> </td>
     <td> </td>
     <td> </td>
     <td>
       <% if missing.day >= 1.week.ago && missing.day <= Time.now %>
          <a role="button" href="/submit/<%=missing.day%>" class="btn btn-default">Resubmit Run</button>
         <%end%>
     </td>
   </tr>

 <% end %>

    <%  @runs.each do |run| %>
    <tr>
      <td>
        <%= run.day.day        %>
      </td>
      <td>
        <%= run.distance       %>
      </td>
      <td>
        <%= run.time           %>
      </td>
      <td>
        <%= run.link %>
      </td>
      <td>
        <% if run.day.day >= 1.week.ago && run.day.day <= Time.now %>

         <a role="button" href="/submit/<%=run.day.day%>" class="btn btn-default">Resubmit Run</button>
          <% end %>
      </td>
    </tr>
<% end %>
</table>
</div>
</div>

app/views/user/update_details.html.erb
<div class="nonheadimage center_div">

<%= @user.email %>
<%= @user.firstname %>
<%= @user.lastname %>
<%= @user.dob %>
<%= @user.reporting_email %>

<%= simple_form_for @user, :url => save_user_path, :method => :patch do |f| %>
  <%= f.input :email %>
  <%= f.input :dob , as: :date, start_year: Date.today.year - 100,
                              end_year: Date.today.year - 3 %>
  <%= f.input :reporting_email %>
  <%= f.button :submit %>
<% end %>
</div>